{
  "hash": "66cd117af7d9a94f713a0c61593baf87",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Análise de Regressão\"\nformat: html\neditor: visual\nexecute: \n  error: false\n  warning: false\n---\n\n\nA análise de regressão é adequada quando queremos entender e prever a relação entre uma variável dependente (Y) e uma ou mais variáveis independentes quatitativa (X). Ela envolve a construção de um modelo matemático que descreverá essa relação funcional. Existem diferentes tipos de modelos de regressão, como regressão linear simples, regressão linear múltipla, regressão não linear, entre outros. Cada um desses modelos pode capturar diferentes formas de relação entre as variáveis.\n\n#### Carregamento dos pacotes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(r4pde)\nlibrary(gsheet)\nlibrary(ggthemes)\nlibrary(patchwork)\nlibrary(lme4)\nlibrary(AgroR)\nlibrary(drc)\nlibrary(ec50estimator)\nlibrary(DT)\nlibrary(stats)\n```\n:::\n\n\n## Regressão linear\n\nA regressão linear é um modelo estatístico fundamental que busca descrever a relação linear entre uma variável dependente (Y) e uma variável independente (X). O modelo matemático é representada pela equação: 𝑌 = 𝛽0 + 𝛽1 ⋅𝑋+ ϵ, onde Y é a variável dependente (ou resposta), X é a variável independente (ou preditora), β1 e β0 são os coeficientes de intercepto e inclinação, e ϵ é o termo de erro, que captura a variação não explicada pelo modelo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## carregando o data frame\nestande <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=401662555\")\ndatatable(estande)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-628a3b4164bee2168ff3\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-628a3b4164bee2168ff3\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\",\"68\",\"69\",\"70\",\"71\",\"72\"],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3],[0,0,0,0,3,3,3,3,6,6,6,6,12,12,12,12,24,24,24,24,48,48,48,48,0,0,0,0,3,3,3,3,6,6,6,6,12,12,12,12,24,24,24,24,48,48,48,48,0,0,0,0,3,3,3,3,6,6,6,6,12,12,12,12,24,24,24,24,48,48,48,48],[1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4],[66,72,50,27,68,79,31,32,58,56,64,33,56,53,50,29,63,44,24,44,48,44,40,39,80,61,75,79,60,47,53,67,31,34,76,59,50,34,61,52,33,38,37,50,34,18,34,40,101,94,93,105,93,97,96,109,99,95,74,89,99,79,84,60,67,68,81,84,49,79,61,58]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>exp<\\/th>\\n      <th>trat<\\/th>\\n      <th>bloco<\\/th>\\n      <th>nplants<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[1,2,3,4]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"exp\",\"targets\":1},{\"name\":\"trat\",\"targets\":2},{\"name\":\"bloco\",\"targets\":3},{\"name\":\"nplants\",\"targets\":4}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nO data frame mostra três experimentos/repetições, onde a variável estande é dependente dos tratamentos.\n\nVisualização dos três Experimentos para ajustar para uma regressão linear usando-se o argumento method = “lm” dentro da função geom_smooth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheme_set(r4pde::theme_r4pde(font_size = 10))\n\nnplants <- estande|>\n  ggplot(aes(trat, nplants))+\n  geom_jitter(width = 0.1, alpha = 0.5)+\n  facet_wrap(~exp)+\n  stat_summary(fun.data = \"mean_cl_boot\", size = 0.5, color = \"steelblue\", alpha = 0.5, size = 2)+\n  geom_smooth (method = \"lm\", se = FALSE)\nnplants\n```\n\n::: {.cell-output-display}\n![](regressao_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n#### Modelo de melhor ajuste para cada experimento\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp1<- estande|>\n  filter(exp==1)\n\nplot1 <- exp1|>\n  ggplot(aes(trat, nplants))+\n  geom_point()+\n  ylim(0, 100)+\n  geom_smooth(method = \"lm\", se = F)\n\nlm1 <- lm(nplants ~trat, data = exp1)\nsummary(lm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = nplants ~ trat, data = exp1)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-25.500  -6.532   1.758   8.573  27.226 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  52.5000     4.2044  12.487 1.84e-11 ***\ntrat         -0.2419     0.1859  -1.301    0.207    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 15 on 22 degrees of freedom\nMultiple R-squared:  0.07148,\tAdjusted R-squared:  0.02928 \nF-statistic: 1.694 on 1 and 22 DF,  p-value: 0.2066\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nexp2<- estande|>\n  filter(exp==2)\n\nplot2 <- exp2|>\n  ggplot(aes(trat, nplants))+\n  geom_point()+\n  ylim(0, 100)+\n  geom_smooth(method = \"lm\", se = F)\n\nlm2 <- lm(nplants ~trat, data = exp2)\nsummary(lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = nplants ~ trat, data = exp2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-25.7816  -7.7150   0.5653   8.1929  19.2184 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  60.9857     3.6304  16.798 4.93e-14 ***\ntrat         -0.7007     0.1605  -4.365 0.000247 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 12.95 on 22 degrees of freedom\nMultiple R-squared:  0.4641,\tAdjusted R-squared:  0.4398 \nF-statistic: 19.05 on 1 and 22 DF,  p-value: 0.0002473\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nexp3<- estande|>\n  filter(exp==3)\n\nplot3 <- exp3|>\n  ggplot(aes(trat, nplants))+\n  geom_point()+\n  ylim(0, 100)+\n  geom_smooth(method = \"lm\", se = F)\n\nlm3 <- lm(nplants ~trat, data = exp3)\nsummary(lm3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = nplants ~ trat, data = exp3)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-26.5887  -3.9597   0.7177   5.5806  19.8952 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  95.7500     2.9529  32.425  < 2e-16 ***\ntrat         -0.7634     0.1306  -5.847 6.97e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.53 on 22 degrees of freedom\nMultiple R-squared:  0.6085,\tAdjusted R-squared:  0.5907 \nF-statistic: 34.19 on 1 and 22 DF,  p-value: 6.968e-06\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot <- plot1|plot2|plot3\nplot\n```\n\n::: {.cell-output-display}\n![](regressao_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nO p-valor do tratamento no experimento 1 indica que o coeficiente angular é igual a 0, aceitando-se assim a hipótese nula. O Adjusted R-squared de 0.02928, indica o acréscimo na variável y em função do aumento da variável x. Já o tratamento 2 não aparenta uma resposta linear ao tratamento. Desta forma podemos transformar os tratamentos em log (pois as doses são crescentes), ou podemos fazer por GLM (Generalized Linear Model - GLM), com as distribuições Gaussiana ou Poisson.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp2<- estande|>\n  filter(exp==2)\nexp2|>\n  ggplot(aes(trat, nplants))+\n  geom_point()+\n  ylim(0, 100)+\n  geom_smooth(se = FALSE)\n```\n\n::: {.cell-output-display}\n![](regressao_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n## Método de Regressão Linear Generalizada (Generalized Linear Model - GLM)\n\nÉ uma extensão do modelo de regressão linear clássico que permite modelar não apenas relações lineares entre variáveis, mas também relações que são mais complexas e não necessariamente em distribuição gaussianas (normais), como a distribuiçã de Poisson.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## GLM com distribuição de Poisson\nglm1 <- glm(nplants ~ trat, family = \"poisson\", data = exp2)\nsummary (glm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = nplants ~ trat, family = \"poisson\", data = exp2)\n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  4.134189   0.037583 110.003  < 2e-16 ***\ntrat        -0.016270   0.002059  -7.901 2.76e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 139.783  on 23  degrees of freedom\nResidual deviance:  69.578  on 22  degrees of freedom\nAIC: 210.24\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(glm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 210.2353\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## GLM com ditribuição de Poisson com dados tranformados em log \nglm2 <- glm(nplants ~ trat, family = poisson(link = \"log\"), data = exp2)\nsummary (glm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = nplants ~ trat, family = poisson(link = \"log\"), \n    data = exp2)\n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  4.134189   0.037583 110.003  < 2e-16 ***\ntrat        -0.016270   0.002059  -7.901 2.76e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 139.783  on 23  degrees of freedom\nResidual deviance:  69.578  on 22  degrees of freedom\nAIC: 210.24\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(glm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 210.2353\n```\n\n\n:::\n:::\n\n\nO modelo GLM com distribuição de Poisson e obteve melhor ajuste, com baixo p-valor e baixo AIC. Porém podemo obtar em ajustes de modelos mistos, se utilizando dos três ensios de uma única vez.\n\n## Modelo Misto\n\nUm modelo misto de regressão combina elementos de modelos de regressão fixa e modelos de efeitos aleatórios. Por exemplo, em um estudo onde as plantas são agrupadas por tempo de irrigação (fator fixo) em locais diferentes (fator aleatório) na incidência de uma doença. Isso permite modelar a estrutura hierárquica dos dados e obter estimativas mais precisas e interpretações mais robustas das relações entre variáveis. Aqui deveremos utilizar a função `lmer` do pacote `lmer`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmix <- lmer(nplants ~trat + (trat | exp),\n            data = estande)\nsummary(mix)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: nplants ~ trat + (trat | exp)\n   Data: estande\n\nREML criterion at convergence: 580.8\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-2.0988 -0.6091  0.1722  0.6360  1.9963 \n\nRandom effects:\n Groups   Name        Variance  Std.Dev. Corr \n exp      (Intercept) 510.68405 22.5983       \n          trat          0.05516  0.2349  -0.82\n Residual             167.91303 12.9581       \nNumber of obs: 72, groups:  exp, 3\n\nFixed effects:\n            Estimate Std. Error t value\n(Intercept)  69.7452    13.2146   5.278\ntrat         -0.5687     0.1643  -3.462\n\nCorrelation of Fixed Effects:\n     (Intr)\ntrat -0.731\noptimizer (nloptwrap) convergence code: 0 (OK)\nModel failed to converge with max|grad| = 0.00274249 (tol = 0.002, component 1)\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## outro exemplo\n\nwn <- WhiteMoldSoybean ## data frame do pacote r4pde\n\nmix <- lmer(inc ~treat + (treat | season),\n            data = wn)\n\nsummary(mix)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: inc ~ treat + (treat | season)\n   Data: wn\n\nREML criterion at convergence: 3257.7\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-1.5718 -0.6809 -0.3052  0.3995  4.2058 \n\nRandom effects:\n Groups   Name        Variance  Std.Dev. Corr \n season   (Intercept)  44.89696  6.7005       \n          treat         0.05739  0.2396  -1.00\n Residual             292.97057 17.1164       \nNumber of obs: 382, groups:  season, 4\n\nFixed effects:\n            Estimate Std. Error t value\n(Intercept)  29.2062     3.8582   7.570\ntreat        -1.4775     0.2931  -5.041\n\nCorrelation of Fixed Effects:\n      (Intr)\ntreat -0.748\noptimizer (nloptwrap) convergence code: 0 (OK)\nboundary (singular) fit: see help('isSingular')\n```\n\n\n:::\n:::\n\n\n## Regressão Quadrática (Regressão linear de segunda ordem)\n\nA regressão quadrática é um modelo estatístico que busca descrever a relação quadrática entre uma variável dependente (Y) e uma variável independente (X). O modelo matemático é representado pela equação: Y = β0 + β1 ⋅ X + β2 ⋅ X2 + ϵ onde, Y é a variável dependente (ou resposta), X é a variável independente (ou preditora), β0, β1 e β1, são os coeficientes de intercepto, inclinação linear e inclinação quadrática, respectivamente, e ϵ é o termo de erro, que captura a variação não explicada pelo modelo.\n\nVamos testar o experimento 2 têm uma tendência de não ter uma resposta linear aos tratamentos\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestande <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=401662555\")\n\n## sobreposição do modelo linear e quadrático \nexp2 %>% \n  ggplot(aes(trat, nplants))+\n  geom_point()+\n  ylim(0,100)+\n  geom_smooth(method = \"lm\",\n              se = F,\n              color = \"steelblue\",\n              formula = y ~ poly(x,2))+\n  geom_smooth(method = \"lm\",\n              se = F,\n              color = \"#e05e00\")\n```\n\n::: {.cell-output-display}\n![](regressao_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n#### Utilização o modelo linear\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm2 <- lm(nplants ~ trat,\n          data = exp2)\n\nsummary(lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = nplants ~ trat, data = exp2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-25.7816  -7.7150   0.5653   8.1929  19.2184 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  60.9857     3.6304  16.798 4.93e-14 ***\ntrat         -0.7007     0.1605  -4.365 0.000247 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 12.95 on 22 degrees of freedom\nMultiple R-squared:  0.4641,\tAdjusted R-squared:  0.4398 \nF-statistic: 19.05 on 1 and 22 DF,  p-value: 0.0002473\n```\n\n\n:::\n:::\n\n\n#### Utilização o modelo quadrático\n\nUtilizar o pacote **`AgroR`** com a função `polynomial`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp2$trat2 <- exp2$trat^2\n\nlm2_quad <- lm(nplants ~ trat + trat2,\n               data = exp2)\nsummary(lm2_quad)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = nplants ~ trat + trat2, data = exp2)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-25.439  -6.019   1.789   8.016  19.561 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 66.30156    4.42097  14.997 1.08e-12 ***\ntrat        -1.77720    0.58467  -3.040  0.00623 ** \ntrat2        0.02223    0.01166   1.906  0.07036 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 12.24 on 21 degrees of freedom\nMultiple R-squared:  0.5432,\tAdjusted R-squared:  0.4997 \nF-statistic: 12.49 on 2 and 21 DF,  p-value: 0.0002675\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwith(exp2, polynomial(trat, nplants, grau = 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n----------------------------------------------------\nRegression Models\n----------------------------------------------------\n               Estimate Std. Error   t value     Pr(>|t|)\n(Intercept) 66.30156250 4.42096799 14.997069 1.079972e-12\ntrat        -1.77719814 0.58467380 -3.039640 6.230050e-03\nI(trat^2)    0.02222876 0.01165948  1.906496 7.036247e-02\n\n----------------------------------------------------\nDeviations from regression\n----------------------------------------------------\n          Df       SSq       MSQ         F      p-value\nLinear     1 3196.2031 3196.2031 21.823293 0.0001899378\nQuadratic  1  544.5029  544.5029  3.717801 0.0697619482\nDeviation  3  509.6690  169.8897  1.159986 0.3523240106\nResidual  18 2636.2500  146.4583                       \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](regressao_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n#### Comparação dos AICs\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAIC(lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 194.9597\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(lm2_quad)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 193.1284\n```\n\n\n:::\n:::\n\n\nPelo menor AIC e maior Adjusted R-squared, o modelo quadrático explica melhor a variação dos dados.\n\n## Regressão de Terceira Ordem\n\nForma de regressão polinomial onde a relação entre a variável dependente Y e a variável independente X é modelada por um polinômio de grau três. Essa técnica permite explicar relações mais complexas e curvas nos dados, oferecendo maior flexibilidade do que a regressão linear ou quadrática.\n\nVamos testar o experimento 3 com um modelo de 3º grau.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwith(exp2, polynomial(trat, nplants, grau = 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n----------------------------------------------------\nRegression Models\n----------------------------------------------------\n                Estimate  Std. Error   t value     Pr(>|t|)\n(Intercept) 70.265143802 5.300440019 13.256474 2.295186e-11\ntrat        -3.609380523 1.514625525 -2.383018 2.720299e-02\nI(trat^2)    0.140522077 0.091192577  1.540938 1.390058e-01\nI(trat^3)   -0.001712445 0.001309648 -1.307561 2.058546e-01\n\n----------------------------------------------------\nDeviations from regression\n----------------------------------------------------\n          Df       SSq       MSQ          F      p-value\nLinear     1 3196.2031 3196.2031 21.8232929 0.0001899378\nQuadratic  1  544.5029  544.5029  3.7178008 0.0697619482\nCubic      1  247.7520  247.7520  1.6916208 0.2097934169\nDeviation  2  261.9170  130.9585  0.8941691 0.4263523326\nResidual  18 2636.2500  146.4583                        \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](regressao_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nEste modelo explica muito bem a variação dos dados, contudo não possui explicação biológica.\n\n## Modelo de Regressão Não-Linear\n\nA regressão não-linear permite uma relação mais complexa e curva entre as variáveis, sendo muito utilizado na fitopatologia em curvas de EC~50~..\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfung <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=465348652\")\n\ndatatable(fung)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-22b2210bf4dd6997720c\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-22b2210bf4dd6997720c\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\",\"68\",\"69\",\"70\",\"71\",\"72\",\"73\",\"74\",\"75\",\"76\",\"77\",\"78\",\"79\",\"80\",\"81\",\"82\",\"83\",\"84\",\"85\",\"86\",\"87\",\"88\",\"89\",\"90\",\"91\",\"92\",\"93\",\"94\",\"95\",\"96\",\"97\",\"98\",\"99\",\"100\",\"101\",\"102\",\"103\",\"104\",\"105\",\"106\",\"107\",\"108\",\"109\",\"110\",\"111\",\"112\",\"113\",\"114\",\"115\",\"116\",\"117\",\"118\",\"119\",\"120\",\"121\",\"122\",\"123\",\"124\",\"125\",\"126\",\"127\",\"128\",\"129\",\"130\",\"131\",\"132\",\"133\",\"134\",\"135\",\"136\",\"137\",\"138\",\"139\",\"140\",\"141\",\"142\",\"143\",\"144\",\"145\",\"146\",\"147\",\"148\",\"149\",\"150\",\"151\",\"152\",\"153\",\"154\",\"155\",\"156\",\"157\",\"158\",\"159\",\"160\",\"161\",\"162\",\"163\",\"164\",\"165\",\"166\",\"167\",\"168\",\"169\",\"170\",\"171\",\"172\",\"173\",\"174\",\"175\",\"176\",\"177\",\"178\",\"179\",\"180\",\"181\",\"182\",\"183\",\"184\",\"185\",\"186\",\"187\",\"188\",\"189\",\"190\",\"191\",\"192\",\"193\",\"194\",\"195\",\"196\",\"197\",\"198\",\"199\",\"200\",\"201\",\"202\",\"203\",\"204\",\"205\",\"206\",\"207\",\"208\",\"209\",\"210\",\"211\",\"212\",\"213\",\"214\",\"215\",\"216\",\"217\",\"218\",\"219\",\"220\",\"221\",\"222\",\"223\",\"224\",\"225\",\"226\",\"227\",\"228\",\"229\",\"230\",\"231\",\"232\",\"233\",\"234\",\"235\",\"236\",\"237\",\"238\",\"239\",\"240\"],[\"FGT05\",\"FGT05\",\"FGT05\",\"FGT05\",\"FGT05\",\"FGT05\",\"FGT05\",\"FGT05\",\"FGT05\",\"FGT05\",\"FGT05\",\"FGT05\",\"FGT06\",\"FGT06\",\"FGT06\",\"FGT06\",\"FGT06\",\"FGT06\",\"FGT06\",\"FGT06\",\"FGT06\",\"FGT06\",\"FGT06\",\"FGT06\",\"FGT07\",\"FGT07\",\"FGT07\",\"FGT07\",\"FGT07\",\"FGT07\",\"FGT07\",\"FGT07\",\"FGT07\",\"FGT07\",\"FGT07\",\"FGT07\",\"FGT28\",\"FGT28\",\"FGT28\",\"FGT28\",\"FGT28\",\"FGT28\",\"FGT28\",\"FGT28\",\"FGT28\",\"FGT28\",\"FGT28\",\"FGT28\",\"FGT29\",\"FGT29\",\"FGT29\",\"FGT29\",\"FGT29\",\"FGT29\",\"FGT29\",\"FGT29\",\"FGT29\",\"FGT29\",\"FGT29\",\"FGT29\",\"FGT33\",\"FGT33\",\"FGT33\",\"FGT33\",\"FGT33\",\"FGT33\",\"FGT33\",\"FGT33\",\"FGT33\",\"FGT33\",\"FGT33\",\"FGT33\",\"FGT34\",\"FGT34\",\"FGT34\",\"FGT34\",\"FGT34\",\"FGT34\",\"FGT34\",\"FGT34\",\"FGT34\",\"FGT34\",\"FGT34\",\"FGT34\",\"FGT35\",\"FGT35\",\"FGT35\",\"FGT35\",\"FGT35\",\"FGT35\",\"FGT35\",\"FGT35\",\"FGT35\",\"FGT35\",\"FGT35\",\"FGT35\",\"FGT42\",\"FGT42\",\"FGT42\",\"FGT42\",\"FGT42\",\"FGT42\",\"FGT42\",\"FGT42\",\"FGT42\",\"FGT42\",\"FGT42\",\"FGT42\",\"FGT43\",\"FGT43\",\"FGT43\",\"FGT43\",\"FGT43\",\"FGT43\",\"FGT43\",\"FGT43\",\"FGT43\",\"FGT43\",\"FGT43\",\"FGT43\",\"152\",\"152\",\"152\",\"152\",\"152\",\"152\",\"152\",\"152\",\"152\",\"152\",\"152\",\"152\",\"153\",\"153\",\"153\",\"153\",\"153\",\"153\",\"153\",\"153\",\"153\",\"153\",\"153\",\"153\",\"164\",\"164\",\"164\",\"164\",\"164\",\"164\",\"164\",\"164\",\"164\",\"164\",\"164\",\"164\",\"165\",\"165\",\"165\",\"165\",\"165\",\"165\",\"165\",\"165\",\"165\",\"165\",\"165\",\"165\",\"169\",\"169\",\"169\",\"169\",\"169\",\"169\",\"169\",\"169\",\"169\",\"169\",\"169\",\"169\",\"170\",\"170\",\"170\",\"170\",\"170\",\"170\",\"170\",\"170\",\"170\",\"170\",\"170\",\"170\",\"186\",\"186\",\"186\",\"186\",\"186\",\"186\",\"186\",\"186\",\"186\",\"186\",\"186\",\"186\",\"187\",\"187\",\"187\",\"187\",\"187\",\"187\",\"187\",\"187\",\"187\",\"187\",\"187\",\"187\",\"188\",\"188\",\"188\",\"188\",\"188\",\"188\",\"188\",\"188\",\"188\",\"188\",\"188\",\"188\",\"189\",\"189\",\"189\",\"189\",\"189\",\"189\",\"189\",\"189\",\"189\",\"189\",\"189\",\"189\"],[2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"RS\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\",\"PR\"],[0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10,0,0,0.05,0.05,0.5,0.5,1,1,5,5,10,10],[1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2],[46,44,18,24,9,11,0,0,0,0,0,0,50,50,43,44,28,27,5,2,2,0,3,0,48,49,45,43,33,31,18,26,3,4,1,0,50,50,30,38,22,18,18,14,8,14,8,8,48,50,39,42,16,16,5,9,0,0,0,0,49,50,38,30,14,4,3,1,0,0,0,0,50,50,31,37,19,15,10,2,1,0,1,0,50,49,40,43,11,16,4,2,0,0,0,0,50,50,44,43,22,26,16,12,0,5,0,0,49,50,46,43,23,25,14,17,1,1,0,0,48,49,42,42,12,19,0,1,0,0,0,0,50,49,48,41,7,11,7,10,0,0,0,0,50,50,45,46,24,26,14,12,0,1,0,0,36,34,33,39,14,20,16,13,3,0,0,0,50,50,35,40,10,13,6,5,1,0,0,0,50,48,47,46,20,18,12,14,1,1,0,0,50,50,47,48,35,31,0,6,0,0,0,0,39,38,30,27,15,13,9,8,4,2,0,0,50,47,41,39,7,9,4,2,0,0,0,0,48,49,48,47,26,24,15,13,1,0,0,0],[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>code<\\/th>\\n      <th>year<\\/th>\\n      <th>trial<\\/th>\\n      <th>state<\\/th>\\n      <th>dose<\\/th>\\n      <th>replicate<\\/th>\\n      <th>germination<\\/th>\\n      <th>...8<\\/th>\\n      <th>...9<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[2,3,5,6,7]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"code\",\"targets\":1},{\"name\":\"year\",\"targets\":2},{\"name\":\"trial\",\"targets\":3},{\"name\":\"state\",\"targets\":4},{\"name\":\"dose\",\"targets\":5},{\"name\":\"replicate\",\"targets\":6},{\"name\":\"germination\",\"targets\":7},{\"name\":\"...8\",\"targets\":8},{\"name\":\"...9\",\"targets\":9}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfung2 <- fung %>% \n  group_by(code, dose) %>% \n  summarise(mean_germ = mean(germination))\n\n## Visualização das médias de germinação dos isolados em função das doses de fungicidas \nfung2 %>% \n  ggplot(aes(dose, mean_germ))+\n  geom_point()+\n  facet_wrap(~ code)\n```\n\n::: {.cell-output-display}\n![](regressao_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n## Modelagem de EC~50~\n\nUtilizaremos o pacote **`drc`**, com a função `drm`. Aqui será importante definir a função (LL2, LL3, LL4) para comparar os modelos e selecionar aquele mais simples (com menor AIC).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFGT05 <- fung2 %>% \n  filter(code ==\"FGT05\")\n\ndrc_fgt05 <- drm(mean_germ ~ dose,\n                 data = FGT05,\n                 fct = LL.3())\n\nsummary(drc_fgt05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel fitted: Log-logistic (ED50 as parameter) with lower limit at 0 (3 parms)\n\nParameter estimates:\n\n               Estimate Std. Error t-value   p-value    \nb:(Intercept)  0.769933   0.198566  3.8775 0.0303750 *  \nd:(Intercept) 44.924753   3.261699 13.7734 0.0008283 ***\ne:(Intercept)  0.044839   0.019291  2.3243 0.1026764    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error:\n\n 3.253867 (3 degrees of freedom)\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(drc_fgt05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 35.02651\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(drc_fgt05)\n```\n\n::: {.cell-output-display}\n![](regressao_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n#### Cáculo da EC~50~\n\n\n::: {.cell}\n\n```{.r .cell-code}\nED(drc_fgt05, 50, interval = \"delta\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nEstimated effective doses\n\n        Estimate Std. Error     Lower     Upper\ne:1:50  0.044839   0.019291 -0.016554  0.106231\n```\n\n\n:::\n:::\n\n\nA EC~50~ (nibe 50% da germinação de espóros) foi estimada em 0.044839.\n\n#### Cálculo da EC~50~ de vários amostras em apenas uma vez\n\nAqui utilizaremos os pacote **`ec50estimator`**. Contudo não é possível selecionar a função de cada modelo para melhor se ajustar a cada tratamento.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_ec50 <- estimate_EC50(mean_germ~dose,\n                         data = fung2,\n                         isolate_col = \"code\",\n                         interval = \"delta\",\n                         fct = drc::LL.3())\ndatatable(df_ec50)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-1baf7a8e4297ad315aed\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-1baf7a8e4297ad315aed\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\"],[\"152\",\"153\",\"164\",\"165\",\"169\",\"170\",\"186\",\"187\",\"188\",\"189\",\"FGT05\",\"FGT06\",\"FGT07\",\"FGT28\",\"FGT29\",\"FGT33\",\"FGT34\",\"FGT35\",\"FGT42\",\"FGT43\"],[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"],[0.4443562921134181,0.2037966428294141,0.5077584385578893,0.5583961307217543,0.1472231103670195,0.375038891910268,0.5797574354294909,0.2156333836945371,0.1529717175030145,0.5310619333335561,0.04483862111325968,0.5449794616939213,0.8877005267670349,0.2260814114629881,0.2360165168159889,0.1048162725943343,0.1477311423537533,0.2031539246265511,0.4500055864313668,0.4958954876770452],[0.07778923986155871,0.04237351183067169,0.04724826570185957,0.1141951132324397,0.009555687975666576,0.04320732845193305,0.01333226808004392,0.03663944561893181,0.004284690501602993,0.02313093593948798,0.01929089015844035,0.03483460212348276,0.07991770412951832,0.03360074200920896,0.03493388051850937,0.01306522050908054,0.04700337288810025,0.0389846040830016,0.05968588958303524,0.06085077057586942],[0.1967962131251725,0.06894521666199757,0.3573933699439433,0.1949763145337218,0.1168126464744155,0.237533889117234,0.5373282081371031,0.09903031535692423,0.1393359200469039,0.4574489717151785,-0.01655360099710266,0.4341202108700156,0.6333667245332928,0.11914885420099,0.1248413178306362,0.06323690985749403,-0.001854568029853731,0.07908751539965447,0.260058447650265,0.302241177684203],[0.6919163711016638,0.3386480689968308,0.6581235071718352,0.9218159469097869,0.1776335742596236,0.5125438947033019,0.6221866627218786,0.33223645203215,0.1666075149591251,0.6046748949519338,0.106230843223622,0.655838712517827,1.142034329000777,0.3330139687249862,0.3471917158013415,0.1463956353311746,0.2973168527373604,0.3272203338534477,0.6399527252124686,0.6895497976698874]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>ID<\\/th>\\n      <th>strata<\\/th>\\n      <th>Estimate<\\/th>\\n      <th>Std..Error<\\/th>\\n      <th>Lower<\\/th>\\n      <th>Upper<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[3,4,5,6]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"ID\",\"targets\":1},{\"name\":\"strata\",\"targets\":2},{\"name\":\"Estimate\",\"targets\":3},{\"name\":\"Std..Error\",\"targets\":4},{\"name\":\"Lower\",\"targets\":5},{\"name\":\"Upper\",\"targets\":6}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n#### Plots das médias da EC~50~ com intervalos de confiança\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_ec50 %>% \n  ggplot(aes(reorder(ID, Estimate), Estimate))+\n  geom_point()+\n  geom_errorbar(aes(ymin = Lower,\n                    ymax = Upper),\n                width = 0.1)+\n  ylim (0, 1.2)+\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](regressao_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "regressao_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/datatables-binding-0.33/datatables.js\"></script>\n<script src=\"site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}